### ISSUE TITLE
Problem with contigs during PDR score calculation

### ISSUE THREAD

**Issue by DolapoA** [MPIIComputationalEpigenetics/WSHPackage#1]
**Version info**
- WSH version (`sessionInfo`): WSH_0.1.3
- OS name and version (`lsb_release -ds`): "CentOS Linux release 7.6.1810 (Core) "

**To Reproduce**
WSH command you have used:
```
require(annotatr)
require(GenomicRanges)
require(WSH)

load(file = "/r_objects/rangesList.rda")


EXTRACTDIR <- "/Bismark_genome/sorted_bams/"

S10_bam <- paste0(EXTRACTDIR,"10_S10_R1_001.preprocessed_bismark_bt2.resorted.dedup.compressed.bam")

# List selected regions
annots <- c("hg19_genes_promoters")

# Build annotations:
annotations = build_annotations(genome = 'hg19', annotations = annots)

# Assesing S10
dm_annotated <- annotate_regions(
	    regions = rangesList[[1]],
	    annotations = annotations,
	    ignore.strand = TRUE,
	    quiet = FALSE)

S10_promoters_unfilt <- GRanges(seqnames = as.vector(dm_annotated@seqnames),
                      ranges = paste0(dm_annotated@ranges@start),"-",dm_annotated@ranges@start))


S10_promoters <- S10_promoters_unfilt[-grep("^G|^J|^K", S10_promoters_unfilt),]

S10_promoters <- S10_promoters[1:10000,]

pdr_10 <- compute.score(bam.file=S10_bam,S10_promoters,score="pdr")

```

**Observed behavior**
Error message or WSH output:
```
Warning message:
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000196.1, GL000197.1, GL000198.1, GL000199.1, GL000200.1, GL000201.1, GL000202.1, GL000203.1, GL000204.1, GL000205.1, GL000206.1, GL0002$
Error: subscript contains out-of-bounds indices
Execution halted
```
**Expected behavior**
Completed PDR score calculation producing bed style output with appended PDR-score column.

**Additional info**
My GRanges object has been reduced in size to 10k CpG sites.

**Comment by schmic05** [comment]
Hi,

Thanks for reporting this. Please note that the package uses UCSC style for the chromosomes, i.e. chr1, chr2, ... instead of 1, 2, ... Might it be that the specified GRanges object has the wrong style and the problem is solved by doing:

```seqlevelsStyle(S10_promoters_unfilt) <- "UCSC"```

Alternatively, it might also be that the seqlevels of the BAM file do not match. Otherwise, would it be possible to share the data with me such that I can figure out the problem?

Best,

Michael

**Comment by DolapoA** [comment]
Hi,

My GRanges objects has UCSC style chromosome names.
For example in my BAM file I see:
```
@SQ	SN:chr10	LN:135534747
@SQ	SN:chr11	LN:135006516
@SQ	SN:chr12	LN:133851895
@SQ	SN:chr13	LN:115169878
@SQ	SN:chr14	LN:107349540
@SQ	SN:chr15	LN:102531392
@SQ	SN:chr16	LN:90354753
@SQ	SN:chr17	LN:81195210
@SQ	SN:chr18	LN:78077248
@SQ	SN:chr19	LN:59128983
@SQ	SN:chr20	LN:63025520
@SQ	SN:chr21	LN:48129895
@SQ	SN:chr22	LN:51304566
@SQ	SN:chrX	LN:155270560
@SQ	SN:chrY	LN:59373566
@SQ	SN:chrM	LN:16569
@SQ	SN:GL877870.2	LN:66021
@SQ	SN:GL877872.1	LN:297485
@SQ	SN:GL383535.1	LN:429806
@SQ	SN:JH159133.1	LN:266316
@SQ	SN:KB663606.1	LN:305900

```
And in my GRanges object I have:
```
             seqnames    ranges strand |
                 <Rle> <IRanges>  <Rle> |
        [1]      chr21   9417767      * |
        [2]      chr21   9437432      * |
        [3]      chr21   9437444      * |
        [4]      chr21   9437458      * |
        [5]      chr21   9437459      * |
        ...        ...       ...    ... .
  [5542337] JH591185.1    117596      * |
  [5542338] JH591185.1    117598      * |
  [5542339] JH591185.1    117603      * |
  [5542340] JH591185.1    117616      * |
  [5542341] JH591185.1    117622      * |
```
I wonder if there is a way to ignore the seqlevels that are not mutually present in the BAM and GRanges object.

D

**Comment by schmic05** [comment]
This should be the default behavior of the findOverlaps function that I use. Have you also tried it with another chromosome than 21? The smaller chromosomes sometimes induce some errors. Also, could you try to make all the CpGs in your GRanges have length 1 as a CpG dinucleotide should have? This might be another problem. It should look like this (taken from the vignette). Somehow it seems, as if the GRanges cannot be overlapped with the BAM file.

```
GRanges object with 10 ranges and 0 metadata columns:
       seqnames          ranges strand
          <Rle>       <IRanges>  <Rle>
   [1]     chr2 2298361-2298362      *
   [2]     chr2 2298554-2298555      *
   [3]     chr2 2298732-2298733      *
   [4]     chr2 2298743-2298744      *
   [5]     chr2 2298787-2298788      *
   [6]     chr2 2298792-2298793      *
   [7]     chr2 2298827-2298828      *
   [8]     chr2 2298884-2298885      *
   [9]     chr2 2298915-2298916      *
  [10]     chr2 2298921-2298922      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

**Comment by DolapoA** [comment]
**Irrelevant error**
I apologise the following error/message is not caused by the WSH package, it is caused by a package called _annotatr_:
```
In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': GL000191.1, GL000192.1, GL000193.1, GL000194.1, GL000195.1, GL000196.1, GL000197.1, GL000198.1, GL000199.1, GL000200.1, GL000201.1, GL000202.1, GL000203.1, GL000204.1, GL000205.1, GL000206.1, GL0002$
```

**New error**
I was able to obtain a result when I selected a 10k portion of chr17 CpG sites, but I did not create ranges with a range of 1 as you prescribed, they were still a range of 0.
However, in the following runs, I have made sure the ranges have a range of 1 and they now look like the example in your vignette, e.g:
```
GRanges object with 2117077 ranges and 0 metadata columns:
            seqnames          ranges strand
               <Rle>       <IRanges>  <Rle>
        [1]    chr21 9825820-9825821      *
        [2]    chr21 9825820-9825821      *
        [3]    chr21 9825829-9825830      *
        [4]    chr21 9825829-9825830      *
        [5]    chr21 9825886-9825887      *
        ...      ...             ...    ...
  [2117073]     chrM     14160-14161      *
  [2117074]     chrM     15927-15928      *
  [2117075]     chrM     15927-15928      *
  [2117076]     chrM     16084-16085      *
  [2117077]     chrM     16084-16085      *

```

Having run the package again on all my chosen CpG sites, I have encountered an error specific to the WSH package which I suspect may be due to the "chrM":
```
Error in `$<-.data.frame`(`*tmp*`, "PDR", value = c(0.342857142857143,  :
  replacement has 2082885 rows, data has 2082960
```  
I checked to see how many rows belong to "chrM" and noticed that the total "chrM" rows was equal to the difference between the 2 row counts in the error message (`2082885 rows, data has 2082960`).

So I'm now running it again, this time removing the "chrM" rows.

**Comment by schmic05** [comment]
No worries, I am very happy that the package at least partially runs. For now, chrM is not really supported, but this should be caught by the package. I will work on this. Please let me know, if you obtain the anticipated results without chrM.

**Comment by DolapoA** [comment]
**WSH tool works**
After removing rows with `chrM` and `contigs` (like `GL877870`, `JH159133` and `KB663606`) I was able to obtain pdr scores for all my samples.

Thanks a lot.
