### ISSUE TITLE
Editing the package

### ISSUE THREAD

**Issue by DolapoA** [MPIIComputationalEpigenetics/WSHPackage#2]
Hi Michael,

Is there a way to edit the tool script a bit? 
I just wanted to change `ignore.strand=TRUE` to `ignore.strand=FALSE` on lines 371, 386 and 388 of the calculate_score.R script.
However, once the package is installed I'm not sure how to edit it as the same files don't show up.

Regards,
Dolapo.

**Comment by schmic05** [comment]
Hi @DolapoA.

In principle, you can either fork this repository and make the changes in your forked version of the package or you can download and modify the source code and then install from source.

However, since your suggestions were easy to implement, I fixed them in the current version of the package with [this commit](https://github.com/MPIIComputationalEpigenetics/WSHPackage/commit/c2e6983bb4473eda28291004da093b74c8e0b7a9) by introducing them as a parameter in the functions. So feel free to upgrade to the newest version of the package and give it a try.

Best,
Michael

**Comment by DolapoA** [comment]
Hi Michael - @schmic05,

Thanks very much, I'll check it out.

Dolapo.

**Comment by DolapoA** [comment]
Hi Michael - @schmic05,

I've downloaded the latest version, how is the ignore.strand parameter actually changed?
I thought it would be done like this but doesn't work:
`compute.score(bam.file=BAM,myRanges,score="pdr", ignore.strand=FALSE)`

Dolapo.

**Comment by schmic05** [comment]
Hi @DolapoA 

I just forgot to add the parameter to this particular function. Could you try again after re-installing?

**Comment by DolapoA** [comment]
Hi Michael - @schmic05,

The reason I wanted to change this parameter is because I wanted to see the effect of not accounting for whether the read is forward or reverse.
The purpose of this was because I've noticed an unusually high amount of CpG positions with PDR scores of 1, suggesting many highly discordant reads. 
This led me to look at a selection of CpG positions which had a PDR score of 1 on the Interactive Genome View (IGV) tool.
What I found in the few CpG positions I looked at, was that these positions with scores of 1, were overwhelmingly concordant with say, the forward read, but the reverse read overlapping the same position was G , instead of a C as seen in the positive read:
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
--------------------C-------------------->
<--------------------G
<--------------------G

So I thought by not ignoring strand information it might avoid classing these reads as disconcordant.

Dolapo.

**Comment by schmic05** [comment]
Hi @DolapoA!

I don't quite see your point. Please note that the package only considers CpG dinucleotides, which are symmetric. This means that a methylated CpG can only be methylated, if you observe a CG in the sequencing reads. It doesn't really matter, whether this information is obtained from the upper or lower strand (i.e. if you observe a TG or a CA). Or am I not getting your point?

Also: PDR looks along the read to check, whether there are both methylated and unmethylated CpGs (and terms them concordant/discordant). The situation you report here is rather for FDRP/qFDRP or Epipolymorphism/Entropy.

**Comment by DolapoA** [comment]
Thanks Michael - @schmic05,
I think I was mistaken.

Dolapo.
