### ISSUE TITLE
What is the difference between compute.score() and calculate.fdrp.score() ?

### ISSUE THREAD

**Issue by realzhang** [MPIIComputationalEpigenetics/WSHPackage#4]
> fdrp.1 <- compute.score(bam.file=example.bam, example.GRanges, score="fdrp", use.sex.chromosomes = TRUE)
> fdrp.2 <- calculate.fdrp.score(  example.bam,  example.GRanges)
> head(fdrp.1)
  chromosome   start     end      FDRP
1       chr2 2298361 2298362 0.1333333
2       chr2 2298554 2298555 0.2567164
3       chr2 2298732 2298733 0.1897436
4       chr2 2298743 2298744 0.2128205
5       chr2 2298787 2298788 0.3801653
6       chr2 2298792 2298793 0.2588076
> head(fdrp.2)
  chromosome   start     end       FDRP
1       chr2 2298361 2298362 0.13333333
2       chr2 2298554 2298555 0.32248521
3       chr2 2298732 2298733 0.14487179
4       chr2 2298743 2298744 0.07179487
5       chr2 2298787 2298788 0.27754533
6       chr2 2298792 2298793 0.16857143

**Comment by realzhang** [comment]
I ran compute.score twice with the same line of code, but got differnet results:

> fdrp.1 <- compute.score(bam.file=example.bam, example.GRanges, score="fdrp")
2021-07-02 16:05:14     1.7  STATUS STARTED Removing Sex chromosomes
2021-07-02 16:05:14     1.7  STATUS COMPLETED Removing Sex chromosomes

2021-07-02 16:05:14     1.7  STATUS STARTED FDRP calculation
2021-07-02 16:06:11     1.7  STATUS COMPLETED FDRP calculation

> head(fdrp.1)
  chromosome   start     end      FDRP
1       chr2 2298361 2298362 0.1333333
2       chr2 2298554 2298555 0.3042254
3       chr2 2298732 2298733 0.1448718
4       chr2 2298743 2298744 0.1871795
5       chr2 2298787 2298788 0.2092050
6       chr2 2298792 2298793 0.4344262

> fdrp.1 <- compute.score(bam.file=example.bam, example.GRanges, score="fdrp")
2021-07-02 16:09:34     1.7  STATUS STARTED Removing Sex chromosomes
2021-07-02 16:09:34     1.7  STATUS COMPLETED Removing Sex chromosomes

2021-07-02 16:09:34     1.7  STATUS STARTED FDRP calculation
2021-07-02 16:10:33     1.7  STATUS COMPLETED FDRP calculation

> head(fdrp.1)
  chromosome   start     end      FDRP
1       chr2 2298361 2298362 0.1333333
2       chr2 2298554 2298555 0.1791045
3       chr2 2298732 2298733 0.1448718
4       chr2 2298743 2298744 0.2102564
5       chr2 2298787 2298788 0.2574526
6       chr2 2298792 2298793 0.2957746

**Comment by schmic05** [comment]
Hi @realzhang 
Thanks for reporting this. There is some stochasticity in the computation of the scores, since we randomly subsample reads from regions with more than ```max.reads```. In highly heterogeneous regions, this can lead to different results. Could you try to set this option to a higher number as the default (40 reads)? Afterwards, the results should be more robust. I.e. do the following:
```set.option(max.reads=100)```.
Hope that clarifies the issue,
Michael

**Comment by realzhang** [comment]
Hi Michael, thank you for the kind reply. I did the test according to the suggestion, please have a look. The values still differ.
> set.option(max.reads=10000000)
> get.option("max.reads")
max.reads 
    1e+07 
> qfdrp.1 <- compute.score(bam.file=example.bam, example.GRanges, score="qfdrp")
> qfdrp.2 <- compute.score(bam.file=example.bam, example.GRanges, score="qfdrp")
> head(qfdrp.1)
  chromosome   start     end     qFDRP
1       chr2 2298361 2298362 0.1333333
2       chr2 2298554 2298555 0.2914286
3       chr2 2298732 2298733 0.0974359
4       chr2 2298743 2298744 0.1064103
5       chr2 2298787 2298788 0.1257555
6       chr2 2298792 2298793 0.1329690
> head(qfdrp.2)
  chromosome   start     end      qFDRP
1       chr2 2298361 2298362 0.13333333
2       chr2 2298554 2298555 0.20144928
3       chr2 2298732 2298733 0.00000000
4       chr2 2298743 2298744 0.10149573
5       chr2 2298787 2298788 0.11275895
6       chr2 2298792 2298793 0.08703704

**Comment by schmic05** [comment]
Thanks @realzhang for reporting this. I fixed the issue with the current commit. Let me know when you face further issues or when the issue is not solved.
