### ISSUE TITLE
Support BED input?

### ISSUE THREAD

**Issue by PanZiwei** [MPIIComputationalEpigenetics/WSHPackage#7]
Hi,
Thanks for the amazing tool. I already have per-read methylation results in BED format with chromosome, start position, end position, read name and methylation frequency for each CpG site.

In this case, instead of using BAM fiel, is it possible to use the BED file as input to calculate WSH scores if possible? Any hints for the implementation? 

Thank you so much for your help!

**Comment by schmic05** [comment]
Hi @PanZiwei 

Thank you for your interest in the package. I have to tell you, though, that this type of input data is not supported for now. For using it, the code would have to substantially change and I don't plan on doing that soon (sorry for that). For your case, I would suggest to either:
1) get access to the BAM files
2) implement the desired score by yourself.
Hope that helps,

Michael
